// Flat-config ESLint setup for Next.js 16 + TypeScript 5 + React 19.
//
// eslint-config-next@16 ships a flat config (an array of config objects),
// so we spread it directly rather than going through FlatCompat. The
// FlatCompat shim trips on the new plugin shape and dies with a circular-
// reference error during config validation.

import nextConfig from "eslint-config-next";

export default [
  ...nextConfig,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      "lib/database.types.ts", // generated by supabase
      "prototype/**", // original design-handoff bundle, not part of the build
      "supabase/**", // SQL + edge function source, ESLint isn't useful here
      "scripts/**",
    ],
  },
  {
    // Plain ESLint rules — apply everywhere.
    rules: {
      // Copy uses ' and " liberally; we render via {String literals}, not raw text.
      "react/no-unescaped-entities": "off",
      // We use plain <img> for OG/avatar previews where Next/Image isn't worth the cost.
      "@next/next/no-img-element": "warn",
      // react-hooks v7 style rules. These will become must-fix once React
      // Compiler ships, but in practice the patterns they flag are fine for
      // this codebase (Date.now() in render for countdown chips, setState in
      // effect for external-sync). Downgrade from error → warn so CI is green.
      "react-hooks/set-state-in-effect": "warn",
      "react-hooks/purity": "warn",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    // TypeScript-only overrides; the @typescript-eslint plugin is registered
    // by eslint-config-next inside its `next/typescript` block (files-scoped
    // to **/*.{ts,tsx}), so we have to match that scope to reach the plugin.
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
];
